# Generated by Django 5.0.3 on 2024-06-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0006_alter_product_category_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='text',
            new_name='username',
        ),
    ]
