# Generated by Django 5.0.3 on 2024-07-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0010_customer_alter_order_customer_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
