# Generated by Django 5.0.3 on 2024-12-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0013_doctor_availableslot_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableslot',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='AvailableSlot',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
